import os
import sys
from openai import OpenAI
from dotenv import load_dotenv

# Why: Load variables from the .env file at application startup.
# Inputs: None
# Outputs: None
load_dotenv()

# Why: Instantiates the OpenAI client based on environment variables.
#      Handles standard OpenAI, LM Studio, and Ollama base URLs.
# Inputs: None
# Outputs: An initialized OpenAI client instance.
def get_openai_client() -> OpenAI:
    api_key = os.getenv("OPENAI_API_KEY")
    base_url = os.getenv("OPENAI_API_BASE")
    
    # If using local services (like Ollama or LM Studio), API key might not be set but we need a placeholder
    if not api_key:
        if base_url:
            # Fallback placeholder key for local endpoints
            api_key = "local-dev-placeholder"
        else:
            print("ERROR: OPENAI_API_KEY environment variable is not set.")
            print("Please create a '.env' file in the 'project' folder and set OPENAI_API_KEY.")
            print("If you are running Ollama or LM Studio, uncomment and configure OPENAI_API_BASE.")
            sys.exit(1)
            
    if base_url:
        return OpenAI(api_key=api_key, base_url=base_url)
    return OpenAI(api_key=api_key)

# Why: Queries the OpenAI-compatible API to get a chat completion response.
# Inputs: 
#   - prompt (str): The user query or task description.
#   - system_message (str): System instructions to steer the model's behavior.
# Outputs:
#   - str: The response text generated by the LLM.
def get_llm_response(prompt: str, system_message: str = "You are a helpful assistant") -> str:
    client = get_openai_client()
    model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    
    # Debug print to show connection parameters
    base_url = os.getenv("OPENAI_API_BASE") or "Default OpenAI Cloud"
    print(f"DEBUG: Connecting to LLM [Endpoint: {base_url}] [Model: {model}]")
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_message},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"\nERROR: LLM request failed. Exception: {e}")
        print("Please check your .env configurations and connection settings.")
        sys.exit(1)
